name: Fastlane Build & Deploy

on:
  push:
    branches: [ "main", "developer" ]
  pull_request:
    branches: [ "main", "developer" ]

jobs:
  # Android Job
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
          
      - name: Install Dependencies
        run: flutter pub get
        
      - name: Build Android
        run: flutter build apk --release
        
      # Uncomment to run Fastlane
      # - name: Run Fastlane
      #   uses: maierj/fastlane-action@v3.1.0
      #   with:
      #     lane: 'test'
      #     subdirectory: 'android'

  # iOS Job (Requires macOS runner, which consumes more minutes)
  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
          
      - name: Install Dependencies
        run: flutter pub get
        
      - name: Build iOS (No Code Signing)
        run: flutter build ios --release --no-codesign
        
      # Uncomment to run Fastlane
      # - name: Run Fastlane
      #   uses: maierj/fastlane-action@v3.1.0
      #   with:
      #     lane: 'beta'
      #     subdirectory: 'ios'
